project_id: my-project-1

vpcs:
  - name: vpc-network-1
    routing_mode: REGIONAL
    subnets:
      private-subnet:
        ip_range: "10.197.41.0/26"
        private_ip_google_access: false
        secondary_ip_ranges:
          - name: gke-pod-range
            ip_range: "172.16.5.0/24"
          - name: gke-svc-range
            ip_range: "172.16.6.0/24"

  - name: vpc-network-2
    routing_mode: REGIONAL
    subnets:
      mgmt-subnet:
        ip_range: "10.197.41.0/26"
        private_ip_google_access: false
        secondary_ip_ranges:
          - name: gke-pod-range
            ip_range: "172.4.5.0/24"
          - name: gke-svc-range
            ip_range: "172.5.6.0/24"
nats:
  - environment: dev
    vpc_id: vpc-netwok-1
    region: europe-west3
    num_nat_ips: 4
    subnet_ids_to_nat:
      - private-subnet


gke_clusters:
  - name: testcluster
    depends_on:
      - vpc-network-1
    argocd: true
    environment: dev
    location: europe-west3-a
    vpc_name: vpc-network-1
    subnetwork: private-subnet
    cluster_secondary_range_name: gke-pod-range
    services_secondary_range_name: gke-svc-range
    deletion_protection: false
    enable_private_endpoint: false
    master_global_access_config: true
    gcp_public_cidrs_access_enabled: true
    node_pools:
      pool-backend:
        min_node_count: 1
        max_node_count: 2
        machine_type: e2-standard-4
        preemptible: false
      pool-frontend:
        min_node_count: 1
        max_node_count: 2
        machine_type: e2-medium
        preemptible: false
    
  - name: testcluster1
    depends_on:
      - vpc-network-2
    argocd: true
    environment: dev
    location: europe-west3-a
    vpc_name: vpc-network-2
    subnetwork: mgmt-subnet
    cluster_secondary_range_name: gke-pod-range
    services_secondary_range_name: gke-svc-range
    deletion_protection: false
    enable_private_endpoint: false
    master_global_access_config: true
    gcp_public_cidrs_access_enabled: true
    node_pools:
      pool-frontend-1:
        min_node_count: 1
        max_node_count: 2
        machine_type: e2-medium
        preemptible: false